//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace timeDistance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Origin { get; set; }
        public int Destination { get; set; }
        public string Station { get; set; }
        public Nullable<double> TotalMile { get; set; }
        public Nullable<double> TotalTime { get; set; }
        public Nullable<double> GMAPDistance { get; set; }
        public Nullable<double> GMAPTime { get; set; }
    }
}
